# Generated by Django 5.2 on 2025-04-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_custom_user_delete_person"),
    ]

    operations = []
