# Generated by Django 5.2 on 2025-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20250422_0143"),
    ]

    operations = [
        migrations.AddField(
            model_name="custom_user",
            name="image",
            field=models.ImageField(
                blank=True, default="def.png", null=True, upload_to="profile_pics/"
            ),
        ),
    ]
