services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Config.wsgi:application" 
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true    
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString

databases:
  - name: django-db
    plan: free
    databaseName: mysite
    user: mysite

        
    